import { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState } from 'react'

const Home: NextPage = () => {

    const router = useRouter()

  const [sub, setSoma] = useState<number>(0)

  const Subtrair = (): number => {
    setSoma(sub - 1)
    return sub
  }

  const RotaSomar = () => {
    router.push("/")
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={() => Subtrair()}>SUBTRAIR</button>
        <p>{sub}</p>
        <button onClick={() => RotaSomar()}>MENOS</button>       
      </main>
    </>
  )
}


export default Home